# Generated by Django 5.2.2 on 2025-07-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_topic_solution_problem_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="level",
            field=models.CharField(default="Easy", max_length=50),
        ),
    ]
