# Generated by Django 5.2.2 on 2025-07-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_problem_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solution",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.RenameField(
            model_name="problem",
            old_name="update",
            new_name="updated",
        ),
        migrations.RenameField(
            model_name="solution",
            old_name="update",
            new_name="updated",
        ),
    ]
