# Generated by Django 5.2.2 on 2025-08-01 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_problem_created_remove_problem_updated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="fellows",
            field=models.ManyToManyField(
                blank=True, related_name="fellows", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
