# Generated by Django 5.2.2 on 2025-08-01 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_problem_fellows"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="fellows",
        ),
        migrations.AddField(
            model_name="problem",
            name="solvers",
            field=models.ManyToManyField(
                blank=True, related_name="solvers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
